# Generated by Django 5.0.6 on 2024-07-11 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desg', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('mob_number', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('linkedin_id', models.URLField(blank=True, null=True)),
                ('github_id', models.URLField(blank=True, null=True)),
                ('profile_pic', models.ImageField(upload_to='profile_pic/')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
            ],
        ),
    ]
