# Generated by Django 5.0.6 on 2024-07-11 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORBApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('years_worked', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desg', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('mob_number', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('linkedin_id', models.URLField(blank=True, null=True)),
                ('github_id', models.URLField(blank=True, null=True)),
                ('profile_pic', models.ImageField(upload_to='profile_pic/')),
                ('summary', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('years_worked', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('skills', models.TextField()),
                ('languages', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillsLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField()),
                ('languages', models.TextField()),
            ],
        ),
    ]
