# Generated by Django 5.0.6 on 2024-06-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=30)),
                ('capital_name', models.CharField(max_length=30)),
                ('population', models.IntegerField()),
                ('Readmore', models.CharField(max_length=30)),
            ],
        ),
    ]
