# Generated by Django 5.0.6 on 2024-06-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeInfoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
