# Generated by Django 5.0.6 on 2024-06-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeDaisApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to='course_images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='logo_duration',
            field=models.ImageField(upload_to='course_logos/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='logo_enrolled',
            field=models.ImageField(upload_to='course_logos/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='logo_lessons',
            field=models.ImageField(upload_to='course_logos/'),
        ),
    ]
