# Generated by Django 5.0.6 on 2024-06-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeDaisApp', '0002_alter_course_img_alter_course_logo_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='logo_duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='logo_enrolled',
        ),
        migrations.RemoveField(
            model_name='course',
            name='logo_lessons',
        ),
    ]
