# Generated by Django 5.0.6 on 2024-06-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeDaisApp', '0004_trainers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainers',
            old_name='img',
            new_name='imgt',
        ),
    ]
