# Generated by Django 5.0.6 on 2024-06-27 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indiaplaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=30)),
                ('i_pic', models.ImageField(upload_to='images/', validators=[django.core.validators.validate_image_file_extension])),
                ('i_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ukplaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uk_name', models.CharField(max_length=30)),
                ('uk_pic', models.ImageField(upload_to='images/', validators=[django.core.validators.validate_image_file_extension])),
                ('uk_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usaplaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_name', models.CharField(max_length=30)),
                ('us_pic', models.ImageField(upload_to='images/', validators=[django.core.validators.validate_image_file_extension])),
                ('us_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
